workflows:
  ios-workflow-manual:
    name: iOS Workflow (Manual Signing)
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      # Para firma manual, configura estos valores en Codemagic UI
      groups:
        - ios_credentials  # Grupo donde guardas certificados en Codemagic
      vars:
        BUNDLE_ID: "com.yourcompany.suraywebedit"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        # Estas variables las defines en Codemagic UI:
        # - CERTIFICATE_PRIVATE_KEY (contenido del .p12 en base64)
        # - CERTIFICATE_PASSWORD
        # - PROVISIONING_PROFILE (contenido del .mobileprovision en base64)
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain for code signing
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          # Estos comandos automáticamente toman los certificados
          # que subiste en Codemagic UI
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Build ipa for distribution
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - tu-email@ejemplo.com
        notify:
          success: true
          failure: true
      # Para publicar manualmente puedes usar:
      # app_store_connect:
      #   api_key: $APP_STORE_CONNECT_KEY_IDENTIFIER
      #   key_id: $APP_STORE_CONNECT_KEY_ID
      #   issuer_id: $APP_STORE_CONNECT_ISSUER_ID
