// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAORFNeZEwdeTBCrsm8YOdNlZ54M49JE8k',
    appId: '1:48825885200:web:703066e836ed404298a095',
    messagingSenderId: '48825885200',
    projectId: 'suray-web',
    authDomain: 'suray-web.firebaseapp.com',
    storageBucket: 'suray-web.firebasestorage.app',
    measurementId: 'G-5CX5GKS0KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQBVi5BE_YpxCaxkCdHIO9gvlr75SdoKk',
    appId: '1:48825885200:android:d0ed79eb0fda949398a095',
    messagingSenderId: '48825885200',
    projectId: 'suray-web',
    storageBucket: 'suray-web.firebasestorage.app',
  );
}
